# -*- coding: utf-8 -*-
"""Pilot_Churn_Analysis.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17Phk2cSFT4TcNRBTWeylaLyf-X6W7ZKN
"""



"""# Connect To BigQuery"""

#libraries that we need
from google.cloud import bigquery
from google.colab import auth


#authenticate
auth.authenticate_user()

#intialize the client for bigquery
project_id='project-analysis-411113'
client=bigquery.Client(project=project_id,location='US')

# get dataset and table
dataset_ref=client.dataset('EmployeeData',project=project_id)
dataset=client.get_dataset(dataset_ref)
table_ref=dataset.table('tbl_hr_data')
table=client.get_table(table_ref)
table.schema

new_table_ref=dataset.table('tbl_new_employees')
new_table=client.get_table(new_table_ref)
new_table.schema

# Convert to DataFrame
df=client.list_rows(table=table).to_dataframe()
df.head(5)

# Convert to DataFrame
df2=client.list_rows(table=new_table).to_dataframe()
df2.head(5)

"""# Build Model

### Install Pycaret
"""

!pip install pycaret

"""# Code and Train Model"""

#get our model
from pycaret.classification import  *

#setup our model
setup(df,target='Quit_the_Company',
      session_id=123,
      ignore_features=['employee_id'],
      categorical_features=['salary','Departments'])

compare_models()

rf_model=create_model('rf')

og_df=predict_model(rf_model)

og_df.head(5)

new_predictions=predict_model(rf_model,data=df2)

new_predictions.head(5)

# Write Back to Bigquery
new_predictions.to_gbq('EmployeeData.pilot_predictions',
                       project_id,
                       chunksize=None,
                       if_exists='replace')

plot_model(rf_model,plot='feature')

# create a feature table
rf_model.feature_names_in_

rf_model.feature_importances_

import pandas as pd
feature_table=pd.DataFrame(zip(rf_model.feature_names_in_,rf_model.feature_importances_),columns=['feature','importance'])

feature_table

feature_table.to_gbq('EmployeeData.feature_table',
                     project_id,
                     chunksize=None,
                     if_exists='replace')

